name: CodeQuality

on:
  push:
    branches: [ master ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.ACTION_TOKEN }}

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.12.0
      with:
        php-version: '7.4'
        tools: php-cs-fixer:2.16.4

    - name: Code Reformatting...
      run: php-cs-fixer fix -v --allow-risky=yes --config=./.php_cs

    - name: Commit Reformated Code
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ github.head_ref }}
        commit_author: lanlin <lanlin1987@github.com>
        commit_message: code reformat workflow
        commit_user_name: lanlin
        commit_user_email: lanlin1987@gmail.com
